# -*- coding: utf-8 -*-
"""InsightAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oW3-dOajnIIyZeGzCO5LVouMLD72zA1w
"""

!pip install -q gradio pandas numpy plotly scikit-learn scipy statsmodels openpyxl reportlab

"""
InsightAI - Smart Data Analytics Platform
Single-file standalone version for Google Colab.
100% offline.
"""
from __future__ import annotations

import os
import traceback
from datetime import datetime
from typing import Dict, Final, List, Optional, Tuple

import gradio as gr
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from scipy import stats
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor


# =============================================================================
# CONFIGURATION
# =============================================================================

APP_NAME: Final[str] = "InsightAI"
APP_TAGLINE: Final[str] = "Upload Any CSV. Discover Insights Instantly."
APP_VERSION: Final[str] = "1.0.0"

COLOR_BG: Final[str] = "#080A14"
COLOR_BG_SECONDARY: Final[str] = "#13162899"
COLOR_CARD: Final[str] = "#131628"
COLOR_CARD_BORDER: Final[str] = "#2A2F4A"
COLOR_PRIMARY: Final[str] = "#7C5CFC"
COLOR_PRIMARY_LIGHT: Final[str] = "#A78BFA"
COLOR_ACCENT: Final[str] = "#1FE3B8"
COLOR_SUCCESS: Final[str] = "#34D399"
COLOR_WARNING: Final[str] = "#FBBF24"
COLOR_DANGER: Final[str] = "#FB7185"
COLOR_TEXT: Final[str] = "#F1F2F8"
COLOR_TEXT_MUTED: Final[str] = "#9499B7"

CHART_COLOR_SEQUENCE: Final[list] = [
    "#7C5CFC", "#1FE3B8", "#FBBF24", "#FB7185",
    "#38BDF8", "#A78BFA", "#34D399", "#F472B6",
    "#FB923C", "#60A5FA",
]

PLOTLY_TEMPLATE: Final[str] = "plotly_dark"

MAX_FILE_SIZE_MB: Final[int] = 200
MAX_ROWS_FULL_RENDER: Final[int] = 50_000
PREVIEW_ROWS: Final[int] = 10
OUTLIER_Z_THRESHOLD: Final[float] = 3.0
HIGH_CORRELATION_THRESHOLD: Final[float] = 0.75
LOW_CORRELATION_THRESHOLD: Final[float] = 0.1
RARE_CATEGORY_THRESHOLD: Final[float] = 0.02
IMBALANCE_THRESHOLD: Final[float] = 0.8
MISSING_WARNING_THRESHOLD: Final[float] = 0.05

SUPPORTED_EXTENSIONS: Final[tuple] = (".csv",)
REPORT_OUTPUT_DIR: Final[str] = "outputs"


# =============================================================================
# STATISTICS UTILITIES
# =============================================================================

def numeric_columns(df: pd.DataFrame) -> List[str]:
    return df.select_dtypes(include=np.number).columns.tolist()


def categorical_columns(df: pd.DataFrame) -> List[str]:
    return df.select_dtypes(include=["object", "string", "category", "bool"]).columns.tolist()


def datetime_columns(df: pd.DataFrame) -> List[str]:
    return df.select_dtypes(include=["datetime64[ns]", "datetime64"]).columns.tolist()


def correlation_matrix(df: pd.DataFrame) -> pd.DataFrame:
    num_cols = numeric_columns(df)
    if len(num_cols) < 2:
        return pd.DataFrame()
    return df[num_cols].corr(numeric_only=True).round(3)


def top_correlations(df: pd.DataFrame, n: int = 5) -> Dict[str, list]:
    corr = correlation_matrix(df)
    if corr.empty:
        return {"highest": [], "lowest": []}

    pairs = []
    cols = corr.columns
    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            val = corr.iloc[i, j]
            if pd.notna(val):
                pairs.append((cols[i], cols[j], val))

    pairs_sorted_desc = sorted(pairs, key=lambda x: abs(x[2]), reverse=True)
    pairs_sorted_asc = sorted(pairs, key=lambda x: abs(x[2]))

    return {
        "highest": pairs_sorted_desc[:n],
        "lowest": pairs_sorted_asc[:n],
    }


def detect_outliers_zscore(df: pd.DataFrame, threshold: float = OUTLIER_Z_THRESHOLD) -> Dict[str, int]:
    result = {}
    for col in numeric_columns(df):
        series = df[col].dropna()
        if len(series) < 3 or series.std() == 0:
            result[col] = 0
            continue
        z_scores = np.abs(stats.zscore(series))
        result[col] = int((z_scores > threshold).sum())
    return result


def detect_outliers_iqr(df: pd.DataFrame) -> Dict[str, int]:
    result = {}
    for col in numeric_columns(df):
        series = df[col].dropna()
        if len(series) < 4:
            result[col] = 0
            continue
        q1, q3 = series.quantile(0.25), series.quantile(0.75)
        iqr = q3 - q1
        lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        result[col] = int(((series < lower) | (series > upper)).sum())
    return result


def skewness_kurtosis(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for col in numeric_columns(df):
        series = df[col].dropna()
        if len(series) < 3:
            continue
        rows.append({
            "Column": col,
            "Skewness": round(float(stats.skew(series)), 3),
            "Kurtosis": round(float(stats.kurtosis(series)), 3),
        })
    return pd.DataFrame(rows)


def normality_check(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for col in numeric_columns(df):
        series = df[col].dropna()
        if len(series) < 8:
            continue
        sample = series.sample(min(len(series), 4999), random_state=42)
        try:
            stat_val, p_value = stats.shapiro(sample)
            rows.append({
                "Column": col,
                "Statistic": round(float(stat_val), 4),
                "P-Value": round(float(p_value), 4),
                "Normally Distributed": "Yes" if p_value > 0.05 else "No",
            })
        except Exception:
            continue
    return pd.DataFrame(rows)


def variance_analysis(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for col in numeric_columns(df):
        series = df[col].dropna()
        if series.empty:
            continue
        rows.append({
            "Column": col,
            "Variance": round(float(series.var()), 3),
            "Std Dev": round(float(series.std()), 3),
            "Mean": round(float(series.mean()), 3),
            "CV (%)": round(float(series.std() / series.mean() * 100), 2) if series.mean() != 0 else np.nan,
        })
    return pd.DataFrame(rows)


def descriptive_summary(df: pd.DataFrame) -> pd.DataFrame:
    num_cols = numeric_columns(df)
    if not num_cols:
        return pd.DataFrame()
    desc = df[num_cols].describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.95]).T.round(3)
    return desc


# =============================================================================
# DATA CLEANING
# =============================================================================

class DataCleaner:
    def __init__(self, df: pd.DataFrame) -> None:
        self.original_shape = df.shape
        self.df = df.copy()
        self.log: List[str] = []

    def remove_duplicates(self) -> "DataCleaner":
        before = len(self.df)
        self.df = self.df.drop_duplicates()
        removed = before - len(self.df)
        if removed:
            self.log.append(f"Removed {removed:,} duplicate row(s).")
        else:
            self.log.append("No duplicate rows found.")
        return self

    def handle_missing_values(self, strategy: str = "smart") -> "DataCleaner":
        total_missing_before = int(self.df.isna().sum().sum())
        if total_missing_before == 0:
            self.log.append("No missing values detected.")
            return self

        if strategy == "drop":
            before = len(self.df)
            self.df = self.df.dropna()
            self.log.append(f"Dropped {before - len(self.df):,} row(s) containing missing values.")
            return self

        for col in self.df.columns:
            if self.df[col].isna().sum() == 0:
                continue
            if pd.api.types.is_numeric_dtype(self.df[col]):
                fill_value = 0 if strategy == "zero" else self.df[col].median()
                self.df[col] = self.df[col].fillna(fill_value)
            else:
                if strategy == "zero":
                    fill_value = "Unknown"
                else:
                    mode_series = self.df[col].mode()
                    fill_value = mode_series.iloc[0] if not mode_series.empty else "Unknown"
                self.df[col] = self.df[col].fillna(fill_value)

        self.log.append(f"Filled {total_missing_before:,} missing value(s) using '{strategy}' strategy.")
        return self

    def convert_date_columns(self) -> "DataCleaner":
        converted = []
        for col in self.df.columns:
            if pd.api.types.is_object_dtype(self.df[col]) or pd.api.types.is_string_dtype(self.df[col]):
                sample = self.df[col].dropna().astype(str).head(20)
                if sample.empty:
                    continue
                try:
                    parsed = pd.to_datetime(sample, errors="coerce", format="mixed")
                    success_ratio = parsed.notna().mean()
                    if success_ratio > 0.8:
                        self.df[col] = pd.to_datetime(self.df[col], errors="coerce", format="mixed")
                        converted.append(col)
                except Exception:
                    continue
        if converted:
            self.log.append(f"Converted to datetime: {', '.join(converted)}.")
        else:
            self.log.append("No date-like columns detected for conversion.")
        return self

    def remove_empty_columns(self) -> "DataCleaner":
        empty_cols = [c for c in self.df.columns if self.df[c].isna().all()]
        if empty_cols:
            self.df = self.df.drop(columns=empty_cols)
            self.log.append(f"Removed fully empty column(s): {', '.join(empty_cols)}.")
        else:
            self.log.append("No fully empty columns found.")
        return self

    def trim_spaces(self) -> "DataCleaner":
        object_cols = self.df.select_dtypes(include=["object", "string"]).columns
        changed = 0
        for col in object_cols:
            stripped = self.df[col].astype(str).str.strip()
            if not stripped.equals(self.df[col].astype(str)):
                changed += 1
            self.df[col] = stripped.replace({"nan": np.nan, "None": np.nan})
        if changed:
            self.log.append(f"Trimmed leading/trailing spaces in {changed} column(s).")
        else:
            self.log.append("No extra whitespace found in text columns.")
        return self

    def normalize_text(self) -> "DataCleaner":
        object_cols = self.df.select_dtypes(include=["object", "string"]).columns
        for col in object_cols:
            self.df[col] = self.df[col].astype(str).str.replace(r"\s+", " ", regex=True)
        self.log.append(f"Normalized whitespace/casing artifacts in {len(object_cols)} text column(s).")
        return self

    def run_full_pipeline(self) -> Tuple[pd.DataFrame, List[str]]:
        (
            self.trim_spaces()
            .remove_empty_columns()
            .remove_duplicates()
            .convert_date_columns()
            .handle_missing_values(strategy="smart")
        )
        return self.df, self.get_report()

    def get_report(self) -> List[str]:
        after_shape = self.df.shape
        summary = (
            f"Shape changed from {self.original_shape[0]:,} rows x "
            f"{self.original_shape[1]} cols -> {after_shape[0]:,} rows x {after_shape[1]} cols."
        )
        return [summary] + self.log


# =============================================================================
# SMART ANALYTICS & INSIGHTS
# =============================================================================

def dataset_health_score(df: pd.DataFrame) -> Dict[str, float]:
    total_cells = df.shape[0] * df.shape[1] if df.size else 1
    missing_ratio = df.isna().sum().sum() / total_cells
    duplicate_ratio = df.duplicated().sum() / max(len(df), 1)

    completeness_score = (1 - missing_ratio) * 100
    uniqueness_score = (1 - duplicate_ratio) * 100
    consistency_score = 100.0

    overall = round(0.5 * completeness_score + 0.3 * uniqueness_score + 0.2 * consistency_score, 1)
    return {
        "overall": min(max(overall, 0), 100),
        "completeness": round(completeness_score, 1),
        "uniqueness": round(uniqueness_score, 1),
        "consistency": round(consistency_score, 1),
    }


def generate_business_insights(df: pd.DataFrame) -> List[str]:
    insights: List[str] = []
    num_cols = numeric_columns(df)
    cat_cols = categorical_columns(df)
    date_cols = datetime_columns(df)

    insights += _missing_value_insights(df)
    insights += _correlation_insights(df, num_cols)
    insights += _distribution_insights(df, num_cols)
    insights += _categorical_insights(df, cat_cols)
    insights += _trend_insights(df, date_cols, num_cols)

    if not insights:
        insights.append("Dataset looks clean and well-balanced - no major issues detected.")

    return insights


def _missing_value_insights(df: pd.DataFrame) -> List[str]:
    out = []
    total = len(df)
    if total == 0:
        return out
    missing_pct = (df.isna().sum() / total).sort_values(ascending=False)
    flagged = missing_pct[missing_pct > MISSING_WARNING_THRESHOLD]
    for col, pct in flagged.items():
        out.append(f"Column '{col}' has {pct*100:.1f}% missing values - consider imputation or removal.")
    dup_pct = df.duplicated().sum() / total
    if dup_pct > 0.01:
        out.append(f"{dup_pct*100:.1f}% of rows are exact duplicates - recommend de-duplication.")
    return out


def _correlation_insights(df: pd.DataFrame, num_cols: List[str]) -> List[str]:
    out = []
    if len(num_cols) < 2:
        return out
    corr_info = top_correlations(df, n=3)
    for a, b, val in corr_info.get("highest", []):
        if abs(val) >= HIGH_CORRELATION_THRESHOLD:
            direction = "positively" if val > 0 else "negatively"
            out.append(f"'{a}' and '{b}' are strongly {direction} correlated (r = {val:.2f}).")
    return out


def _distribution_insights(df: pd.DataFrame, num_cols: List[str]) -> List[str]:
    out = []
    outliers = detect_outliers_iqr(df)
    for col, count in outliers.items():
        if count > 0:
            pct = count / max(len(df), 1) * 100
            if pct > 1:
                out.append(f"'{col}' contains {count} outlier(s) ({pct:.1f}% of data) using the IQR method.")

    for col in num_cols:
        series = df[col].dropna()
        if series.empty:
            continue
        mean_val, max_val, min_val = series.mean(), series.max(), series.min()
        out.append(f"'{col}' averages {mean_val:,.2f} (range: {min_val:,.2f} -> {max_val:,.2f}).")
    return out[: min(len(out), 8)]


def _categorical_insights(df: pd.DataFrame, cat_cols: List[str]) -> List[str]:
    out = []
    total = len(df)
    if total == 0:
        return out
    for col in cat_cols:
        series = df[col].dropna()
        if series.empty:
            continue
        value_counts = series.value_counts(normalize=True)
        top_value, top_share = value_counts.index[0], value_counts.iloc[0]

        if top_share >= IMBALANCE_THRESHOLD:
            out.append(f"Column '{col}' is highly imbalanced - '{top_value}' makes up {top_share*100:.1f}% of all records.")
        else:
            out.append(f"The most frequent value in '{col}' is '{top_value}' ({top_share*100:.1f}% share).")

        rare = value_counts[value_counts < RARE_CATEGORY_THRESHOLD]
        if len(rare) > 0:
            out.append(f"'{col}' has {len(rare)} rare categor{'y' if len(rare)==1 else 'ies'} (each under {RARE_CATEGORY_THRESHOLD*100:.0f}% share).")
    return out[: min(len(out), 8)]


def _trend_insights(df: pd.DataFrame, date_cols: List[str], num_cols: List[str]) -> List[str]:
    out = []
    if not date_cols or not num_cols:
        return out

    date_col = date_cols[0]
    temp = df[[date_col] + num_cols].dropna(subset=[date_col]).sort_values(date_col)
    if temp.empty or len(temp) < 4:
        return out

    for metric in num_cols[:3]:
        series = temp[metric].dropna()
        if len(series) < 4:
            continue
        first_half = series.iloc[: len(series) // 2].mean()
        second_half = series.iloc[len(series) // 2:].mean()
        if first_half == 0 or pd.isna(first_half):
            continue
        growth = (second_half - first_half) / abs(first_half) * 100
        direction = "increased" if growth > 0 else "decreased"
        out.append(f"'{metric}' has {direction} by {abs(growth):.1f}% over the observed time period (based on '{date_col}').")
    return out


def generate_recommendations(df: pd.DataFrame) -> List[str]:
    recs: List[str] = []
    total = len(df)
    if total == 0:
        return ["Upload a non-empty dataset to receive recommendations."]

    missing_pct = df.isna().sum().sum() / (df.shape[0] * df.shape[1])
    if missing_pct > MISSING_WARNING_THRESHOLD:
        recs.append("Run the 'Handle Missing Values' cleaning tool before deeper analysis.")

    if df.duplicated().sum() > 0:
        recs.append("Remove duplicate rows to avoid skewed aggregate statistics.")

    num_cols = numeric_columns(df)
    outliers = detect_outliers_iqr(df)
    if any(v > 0 for v in outliers.values()):
        recs.append("Investigate flagged outliers - they may be data-entry errors or genuine extreme events.")

    cat_cols = categorical_columns(df)
    for col in cat_cols:
        series = df[col].dropna()
        if series.empty:
            continue
        if series.value_counts(normalize=True).iloc[0] >= IMBALANCE_THRESHOLD:
            recs.append(f"'{col}' is imbalanced - consider stratified sampling for any ML model using it.")
            break

    if len(num_cols) >= 2:
        recs.append("Explore the Correlation Matrix tab to identify redundant or highly related features.")

    if not recs:
        recs.append("Dataset is in good shape - proceed directly to visualization and modeling.")

    return recs


def compute_kpis(df: pd.DataFrame) -> Dict[str, str]:
    num_cols = numeric_columns(df)
    cat_cols = categorical_columns(df)
    health = dataset_health_score(df)
    memory_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)

    return {
        "Rows": f"{len(df):,}",
        "Columns": f"{df.shape[1]:,}",
        "Numeric Features": f"{len(num_cols):,}",
        "Categorical Features": f"{len(cat_cols):,}",
        "Missing Values": f"{int(df.isna().sum().sum()):,}",
        "Duplicate Rows": f"{int(df.duplicated().sum()):,}",
        "Memory Usage": f"{memory_mb:.2f} MB",
        "Data Quality Score": f"{health['overall']}/100",
    }


# =============================================================================
# PLOTLY CHARTS
# =============================================================================

def _style(fig: go.Figure, title: str) -> go.Figure:
    fig.update_layout(
        template=PLOTLY_TEMPLATE,
        title=dict(text=title, font=dict(size=16, color=COLOR_TEXT)),
        paper_bgcolor=COLOR_BG,
        plot_bgcolor=COLOR_CARD,
        font=dict(color=COLOR_TEXT, family="Inter, sans-serif"),
        margin=dict(l=40, r=30, t=60, b=40),
        legend=dict(bgcolor="rgba(0,0,0,0)"),
        colorway=CHART_COLOR_SEQUENCE,
    )
    return fig


def _sample_if_large(df: pd.DataFrame) -> pd.DataFrame:
    if len(df) > MAX_ROWS_FULL_RENDER:
        return df.sample(MAX_ROWS_FULL_RENDER, random_state=42)
    return df


def bar_chart(df: pd.DataFrame, cat_col: str, num_col: Optional[str] = None, top_n: int = 12) -> Optional[go.Figure]:
    if cat_col not in df.columns:
        return None
    data = df.copy()
    if num_col and num_col in data.columns:
        grouped = data.groupby(cat_col)[num_col].sum().sort_values(ascending=False).head(top_n)
        fig = px.bar(grouped, x=grouped.index, y=grouped.values, labels={"x": cat_col, "y": num_col})
        title = f"{num_col} by {cat_col} (Top {top_n})"
    else:
        counts = data[cat_col].value_counts().head(top_n)
        fig = px.bar(counts, x=counts.index, y=counts.values, labels={"x": cat_col, "y": "Count"})
        title = f"Top Categories - {cat_col}"
    return _style(fig, title)


def line_chart(df: pd.DataFrame, date_col: str, num_col: str) -> Optional[go.Figure]:
    if date_col not in df.columns or num_col not in df.columns:
        return None
    data = df[[date_col, num_col]].dropna().sort_values(date_col)
    if data.empty:
        return None
    fig = px.line(data, x=date_col, y=num_col, markers=True)
    return _style(fig, f"{num_col} Over Time")


def pie_chart(df: pd.DataFrame, cat_col: str, top_n: int = 8) -> Optional[go.Figure]:
    if cat_col not in df.columns:
        return None
    counts = df[cat_col].value_counts().head(top_n)
    fig = px.pie(values=counts.values, names=counts.index, hole=0.45)
    return _style(fig, f"Share Distribution - {cat_col}")


def scatter_plot(df: pd.DataFrame, x_col: str, y_col: str, color_col: Optional[str] = None) -> Optional[go.Figure]:
    if x_col not in df.columns or y_col not in df.columns:
        return None
    data = _sample_if_large(df)
    fig = px.scatter(
        data, x=x_col, y=y_col,
        color=color_col if color_col in data.columns else None,
        trendline="ols" if len(data) > 5 else None,
        opacity=0.75,
    )
    return _style(fig, f"{y_col} vs {x_col}")


def histogram(df: pd.DataFrame, num_col: str, bins: int = 30) -> Optional[go.Figure]:
    if num_col not in df.columns:
        return None
    fig = px.histogram(df, x=num_col, nbins=bins)
    return _style(fig, f"Distribution of {num_col}")


def box_plot(df: pd.DataFrame, num_col: str, cat_col: Optional[str] = None) -> Optional[go.Figure]:
    if num_col not in df.columns:
        return None
    fig = px.box(df, y=num_col, x=cat_col if cat_col in df.columns else None, points="outliers")
    return _style(fig, f"Box Plot - {num_col}")


def violin_plot(df: pd.DataFrame, num_col: str, cat_col: Optional[str] = None) -> Optional[go.Figure]:
    if num_col not in df.columns:
        return None
    fig = px.violin(df, y=num_col, x=cat_col if cat_col in df.columns else None, box=True, points=False)
    return _style(fig, f"Violin Plot - {num_col}")


def correlation_heatmap(df: pd.DataFrame) -> Optional[go.Figure]:
    corr = correlation_matrix(df)
    if corr.empty:
        return None
    fig = px.imshow(
        corr, text_auto=True, color_continuous_scale="Viridis",
        aspect="auto", zmin=-1, zmax=1,
    )
    return _style(fig, "Correlation Matrix")


def pair_plot_matrix(df: pd.DataFrame, num_cols: Optional[List[str]] = None) -> Optional[go.Figure]:
    num_cols = num_cols or numeric_columns(df)
    num_cols = num_cols[:5]
    if len(num_cols) < 2:
        return None
    data = _sample_if_large(df)
    fig = px.scatter_matrix(data, dimensions=num_cols)
    return _style(fig, "Pair Plot - Numeric Features")


def top_categories_chart(df: pd.DataFrame, cat_col: str, top_n: int = 10) -> Optional[go.Figure]:
    return bar_chart(df, cat_col, num_col=None, top_n=top_n)


def time_series_chart(df: pd.DataFrame, date_col: str, num_col: str, freq: str = "ME") -> Optional[go.Figure]:
    if date_col not in df.columns or num_col not in df.columns:
        return None
    data = df[[date_col, num_col]].dropna().copy()
    if data.empty:
        return None
    data = data.set_index(date_col).resample(freq)[num_col].sum().reset_index()
    fig = px.area(data, x=date_col, y=num_col)
    return _style(fig, f"{num_col} Trend ({freq})")


def auto_select_charts(df: pd.DataFrame) -> dict:
    figs = {}
    num_cols = numeric_columns(df)
    cat_cols = categorical_columns(df)
    date_cols = datetime_columns(df)

    if cat_cols and num_cols:
        figs["Bar Chart"] = bar_chart(df, cat_cols[0], num_cols[0])
    elif cat_cols:
        figs["Bar Chart"] = bar_chart(df, cat_cols[0])

    if date_cols and num_cols:
        figs["Line Chart"] = line_chart(df, date_cols[0], num_cols[0])
        figs["Time Series"] = time_series_chart(df, date_cols[0], num_cols[0], freq="ME")

    if cat_cols:
        figs["Pie Chart"] = pie_chart(df, cat_cols[0])
        figs["Top Categories"] = top_categories_chart(df, cat_cols[0])

    if len(num_cols) >= 2:
        figs["Scatter Plot"] = scatter_plot(df, num_cols[0], num_cols[1])
        figs["Correlation Heatmap"] = correlation_heatmap(df)
        figs["Pair Plot"] = pair_plot_matrix(df, num_cols)

    if num_cols:
        figs["Histogram"] = histogram(df, num_cols[0])
        figs["Box Plot"] = box_plot(df, num_cols[0], cat_cols[0] if cat_cols else None)
        figs["Violin Plot"] = violin_plot(df, num_cols[0], cat_cols[0] if cat_cols else None)

    return {k: v for k, v in figs.items() if v is not None}


# =============================================================================
# FORECASTING
# =============================================================================

def detect_date_column(df: pd.DataFrame) -> Optional[str]:
    datetime_cols = df.select_dtypes(include=["datetime64[ns]", "datetime64"]).columns.tolist()
    if datetime_cols:
        return datetime_cols[0]
    return None


def prepare_series(df: pd.DataFrame, date_col: str, value_col: str, freq: str = "ME") -> pd.Series:
    data = df[[date_col, value_col]].dropna().sort_values(date_col)
    data = data.set_index(date_col)
    series = data[value_col].resample(freq).sum()
    return series


def moving_average(series: pd.Series, window: int = 3) -> pd.Series:
    return series.rolling(window=window, min_periods=1).mean()


def compute_growth_rate(series: pd.Series) -> float:
    series = series.dropna()
    if len(series) < 2 or series.iloc[0] == 0:
        return 0.0
    return float((series.iloc[-1] - series.iloc[0]) / abs(series.iloc[0]) * 100)


def forecast_series(series: pd.Series, periods: int = 6) -> Tuple[pd.Series, str]:
    series = series.dropna()
    if len(series) < 4:
        return pd.Series(dtype=float), "insufficient_data"

    try:
        from statsmodels.tsa.holtwinters import Holt
        model = Holt(series, initialization_method="estimated").fit()
        forecast_vals = model.forecast(periods)
        return forecast_vals, "Holt Linear Trend (statsmodels)"
    except Exception:
        x = np.arange(len(series))
        coeffs = np.polyfit(x, series.values, deg=1)
        future_x = np.arange(len(series), len(series) + periods)
        forecast_vals = np.polyval(coeffs, future_x)
        freq = pd.infer_freq(series.index) or "M"
        future_index = pd.date_range(start=series.index[-1], periods=periods + 1, freq=freq)[1:]
        return pd.Series(forecast_vals, index=future_index), "Linear Regression (fallback)"


def build_forecast_chart(series: pd.Series, forecast_vals: pd.Series, value_col: str, method: str) -> go.Figure:
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=series.index, y=series.values, mode="lines+markers", name="Historical",
        line=dict(color=CHART_COLOR_SEQUENCE[0], width=2),
    ))
    if not forecast_vals.empty:
        fig.add_trace(go.Scatter(
            x=forecast_vals.index, y=forecast_vals.values, mode="lines+markers",
            name=f"Forecast ({method})",
            line=dict(color=CHART_COLOR_SEQUENCE[3], width=2, dash="dash"),
        ))
    ma = moving_average(series, window=3)
    fig.add_trace(go.Scatter(
        x=ma.index, y=ma.values, mode="lines", name="Moving Average (3)",
        line=dict(color=CHART_COLOR_SEQUENCE[2], width=1.5, dash="dot"),
    ))

    fig.update_layout(
        template=PLOTLY_TEMPLATE,
        title=dict(text=f"Forecast - {value_col}", font=dict(size=16, color=COLOR_TEXT)),
        paper_bgcolor=COLOR_BG,
        plot_bgcolor=COLOR_CARD,
        font=dict(color=COLOR_TEXT, family="Inter, sans-serif"),
        margin=dict(l=40, r=30, t=60, b=40),
        legend=dict(bgcolor="rgba(0,0,0,0)"),
    )
    return fig


def detect_seasonality(series: pd.Series, period: int = 12) -> Optional[str]:
    series = series.dropna()
    if len(series) < period * 2:
        return None
    try:
        autocorr = series.autocorr(lag=period)
        if pd.isna(autocorr):
            return None
        if autocorr > 0.5:
            return f"Likely seasonal pattern detected (lag-{period} autocorrelation = {autocorr:.2f})."
        return f"No strong seasonality detected (lag-{period} autocorrelation = {autocorr:.2f})."
    except Exception:
        return None


# =============================================================================
# MACHINE LEARNING
# =============================================================================

def _usable_numeric_columns(df: pd.DataFrame, exclude: Optional[str] = None, max_missing_frac: float = 0.5) -> List[str]:
    """Numeric columns suitable as ML features - excludes the target column
    and any column that is empty or mostly missing (e.g. a fully-blank
    'notes' column), which would otherwise wipe out every row once dropna()
    is applied across all numeric columns together."""
    if len(df) == 0:
        return []
    cols = []
    for c in numeric_columns(df):
        if c == exclude:
            continue
        missing_frac = df[c].isna().sum() / len(df)
        if missing_frac < max_missing_frac:
            cols.append(c)
    return cols


def _clean_numeric_frame(df: pd.DataFrame) -> pd.DataFrame:
    num_cols = _usable_numeric_columns(df)
    data = df[num_cols].dropna()
    return data


def run_kmeans(df: pd.DataFrame, n_clusters: int = 3) -> Tuple[Optional[go.Figure], str]:
    data = _clean_numeric_frame(df)
    if data.shape[1] < 2 or len(data) < n_clusters:
        return None, "Need at least 2 numeric columns and enough rows for clustering."

    scaled = StandardScaler().fit_transform(data)
    model = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    labels = model.fit_predict(scaled)

    pca = PCA(n_components=2, random_state=42)
    coords = pca.fit_transform(scaled)
    plot_df = pd.DataFrame(coords, columns=["PC1", "PC2"])
    plot_df["Cluster"] = labels.astype(str)

    fig = px.scatter(plot_df, x="PC1", y="PC2", color="Cluster")
    fig = _style(fig, f"K-Means Clustering (k={n_clusters}, PCA-projected)")
    summary = (
        f"K-Means formed {n_clusters} clusters across {data.shape[1]} numeric features "
        f"({len(data):,} rows used). Explained variance (2D PCA projection): "
        f"{pca.explained_variance_ratio_.sum()*100:.1f}%."
    )
    return fig, summary


def run_linear_regression(df: pd.DataFrame, target_col: str) -> Tuple[Optional[go.Figure], str]:
    num_cols = _usable_numeric_columns(df, exclude=target_col)
    if target_col not in df.columns or not num_cols:
        return None, "Select a numeric target column and ensure other numeric features exist."

    data = df[num_cols + [target_col]].dropna()
    if len(data) < 10:
        return None, "Not enough rows after dropping missing values to fit a regression model."

    X, y = data[num_cols], data[target_col]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = LinearRegression().fit(X_train, y_train)
    preds = model.predict(X_test)

    r2 = r2_score(y_test, preds)
    rmse = float(np.sqrt(mean_squared_error(y_test, preds)))

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=y_test, y=preds, mode="markers", name="Predicted vs Actual",
                              marker=dict(color=CHART_COLOR_SEQUENCE[0], opacity=0.7)))
    min_v, max_v = float(min(y_test.min(), preds.min())), float(max(y_test.max(), preds.max()))
    fig.add_trace(go.Scatter(x=[min_v, max_v], y=[min_v, max_v], mode="lines",
                              name="Perfect Prediction", line=dict(color=CHART_COLOR_SEQUENCE[3], dash="dash")))
    fig = _style(fig, f"Linear Regression - Predicting {target_col}")

    summary = (
        f"Linear Regression trained on {len(num_cols)} feature(s). "
        f"R2 = {r2:.3f}, RMSE = {rmse:,.2f} on the held-out test set ({len(y_test)} rows)."
    )
    return fig, summary


def run_random_forest_importance(df: pd.DataFrame, target_col: str) -> Tuple[Optional[go.Figure], str]:
    if target_col not in df.columns:
        return None, "Target column not found."

    num_cols = _usable_numeric_columns(df, exclude=target_col)
    if not num_cols:
        return None, "Need at least one other numeric column besides the target."

    data = df[num_cols + [target_col]].dropna()
    if len(data) < 10:
        return None, "Not enough rows to compute feature importance."

    X = data[num_cols]
    y = data[target_col]

    is_numeric_target = pd.api.types.is_numeric_dtype(y)
    unique_count = y.nunique()
    if not is_numeric_target and unique_count > 50:
        return None, (
            f"'{target_col}' has {unique_count} unique values (looks like an ID or date column) - "
            f"please choose a column with fewer distinct categories, or a numeric column instead."
        )

    is_classification = (not is_numeric_target) or unique_count <= 10
    if is_classification:
        y_encoded = LabelEncoder().fit_transform(y.astype(str))
        model = RandomForestClassifier(n_estimators=150, random_state=42).fit(X, y_encoded)
    else:
        model = RandomForestRegressor(n_estimators=150, random_state=42).fit(X, y)

    importance = pd.Series(model.feature_importances_, index=num_cols).sort_values(ascending=False)
    fig = px.bar(importance, x=importance.values, y=importance.index, orientation="h")
    fig = _style(fig, f"Random Forest Feature Importance (target: {target_col})")

    top_feature = importance.index[0]
    summary = f"Most important feature for predicting '{target_col}' is '{top_feature}' ({importance.iloc[0]*100:.1f}% importance)."
    return fig, summary


def run_pca(df: pd.DataFrame, n_components: int = 2) -> Tuple[Optional[go.Figure], str]:
    data = _clean_numeric_frame(df)
    if data.shape[1] < 2:
        return None, "Need at least 2 numeric columns for PCA."

    n_components = min(n_components, data.shape[1])
    scaled = StandardScaler().fit_transform(data)
    pca = PCA(n_components=n_components, random_state=42)
    coords = pca.fit_transform(scaled)

    plot_df = pd.DataFrame(coords[:, :2], columns=["PC1", "PC2"])
    fig = px.scatter(plot_df, x="PC1", y="PC2", opacity=0.7)
    fig = _style(fig, "PCA Projection (2D)")

    explained = pca.explained_variance_ratio_
    summary = "Explained variance: " + ", ".join(
        f"PC{i+1}={v*100:.1f}%" for i, v in enumerate(explained)
    )
    return fig, summary


def run_decision_tree(df: pd.DataFrame, target_col: str, max_depth: int = 4) -> Tuple[Optional[go.Figure], str]:
    if target_col not in df.columns:
        return None, "Target column not found."

    num_cols = _usable_numeric_columns(df, exclude=target_col)
    if not num_cols:
        return None, "Need numeric feature columns besides the target."

    data = df[num_cols + [target_col]].dropna()
    if len(data) < 10:
        return None, "Not enough rows to train a decision tree."

    X = data[num_cols]
    y = data[target_col]
    is_numeric_target = pd.api.types.is_numeric_dtype(y)
    unique_count = y.nunique()

    if not is_numeric_target and unique_count > 50:
        return None, (
            f"'{target_col}' has {unique_count} unique values (looks like an ID or date column) - "
            f"please choose a column with fewer distinct categories, or a numeric column for regression."
        )

    is_classification = (not is_numeric_target) or unique_count <= 10

    if is_classification:
        # Fit the encoder on the FULL target column (not just the training split)
        # so that rare categories present only in the test split never trigger
        # an "unseen label" error.
        le = LabelEncoder()
        y_encoded_full = pd.Series(le.fit_transform(y.astype(str)), index=y.index)
        X_train, X_test, y_train_enc, y_test_enc = train_test_split(
            X, y_encoded_full, test_size=0.2, random_state=42
        )
        model = DecisionTreeClassifier(max_depth=max_depth, random_state=42).fit(X_train, y_train_enc)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test_enc, preds)

        cm = confusion_matrix(y_test_enc, preds)
        fig = px.imshow(cm, text_auto=True, color_continuous_scale="Viridis",
                         labels=dict(x="Predicted", y="Actual"))
        fig = _style(fig, f"Confusion Matrix - Decision Tree (target: {target_col})")
        summary = f"Decision Tree Classifier accuracy: {acc*100:.1f}% on {len(y_test_enc)} held-out rows."
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        model = DecisionTreeRegressor(max_depth=max_depth, random_state=42).fit(X_train, y_train)
        preds = model.predict(X_test)
        r2 = r2_score(y_test, preds)
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=y_test, y=preds, mode="markers",
                                  marker=dict(color=CHART_COLOR_SEQUENCE[1], opacity=0.7)))
        fig = _style(fig, f"Decision Tree Regression - {target_col} (R2={r2:.3f})")
        summary = f"Decision Tree Regressor R2 score: {r2:.3f} on {len(y_test)} held-out rows."

    return fig, summary


# =============================================================================
# EXPORT UTILITIES
# =============================================================================

def _ensure_output_dir() -> str:
    os.makedirs(REPORT_OUTPUT_DIR, exist_ok=True)
    return REPORT_OUTPUT_DIR


def export_cleaned_csv(df: pd.DataFrame, filename: str = "cleaned_dataset.csv") -> str:
    out_dir = _ensure_output_dir()
    path = os.path.join(out_dir, filename)
    df.to_csv(path, index=False)
    return path


def export_business_pdf_report(
    df: pd.DataFrame,
    kpis: dict,
    insights: List[str],
    recommendations: List[str],
    dataset_name: str = "Uploaded Dataset",
    filename: str = "InsightAI_Business_Report.pdf",
) -> str:
    out_dir = _ensure_output_dir()
    path = os.path.join(out_dir, filename)

    doc = SimpleDocTemplate(
        path, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleCustom", parent=styles["Title"], textColor=colors.HexColor("#5B3FE0"), fontSize=24,
    )
    heading_style = ParagraphStyle(
        "HeadingCustom", parent=styles["Heading2"], textColor=colors.HexColor("#7C5CFC"),
        spaceBefore=14, spaceAfter=8,
    )
    body_style = ParagraphStyle("BodyCustom", parent=styles["BodyText"], fontSize=10.5, leading=15)

    elements = []
    elements.append(Paragraph(f"{APP_NAME} - Business Intelligence Report", title_style))
    elements.append(Paragraph(f"Dataset: {dataset_name}", styles["Normal"]))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("Key Performance Indicators", heading_style))
    kpi_rows = [["Metric", "Value"]] + [[k, v] for k, v in kpis.items()]
    kpi_table = Table(kpi_rows, colWidths=[8 * cm, 6 * cm])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#5B3FE0")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 16))

    elements.append(Paragraph("Business Insights", heading_style))
    if insights:
        for insight in insights:
            clean = insight.replace("**", "")
            elements.append(Paragraph(f"- {clean}", body_style))
            elements.append(Spacer(1, 4))
    else:
        elements.append(Paragraph("No notable insights detected.", body_style))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Recommendations", heading_style))
    for rec in recommendations:
        clean = rec.replace("**", "")
        elements.append(Paragraph(f"- {clean}", body_style))
        elements.append(Spacer(1, 4))

    elements.append(PageBreak())

    elements.append(Paragraph("Dataset Preview (first 10 rows)", heading_style))
    preview = df.head(10)
    preview_cols = list(preview.columns)[:6]
    preview_data = [preview_cols] + preview[preview_cols].astype(str).values.tolist()
    preview_table = Table(preview_data, repeatRows=1)
    preview_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#5B3FE0")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
    ]))
    elements.append(preview_table)

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        f"Report generated automatically by {APP_NAME} - 100% offline, rule-based analytics engine.",
        styles["Italic"],
    ))

    doc.build(elements)
    return path


def export_summary_text_report(
    kpis: dict, insights: List[str], recommendations: List[str],
    filename: str = "InsightAI_Summary_Report.txt",
) -> str:
    out_dir = _ensure_output_dir()
    path = os.path.join(out_dir, filename)
    lines = ["=" * 60, f"{APP_NAME} - Summary Report", "=" * 60, ""]
    lines.append("KEY PERFORMANCE INDICATORS")
    lines.append("-" * 30)
    for k, v in kpis.items():
        lines.append(f"{k}: {v}")
    lines.append("")
    lines.append("BUSINESS INSIGHTS")
    lines.append("-" * 30)
    for insight in insights:
        lines.append(f"- {insight.replace('**', '')}")
    lines.append("")
    lines.append("RECOMMENDATIONS")
    lines.append("-" * 30)
    for rec in recommendations:
        lines.append(f"- {rec.replace('**', '')}")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


# =============================================================================
# HTML RENDERING HELPERS
# =============================================================================

_KPI_ICONS = {
    "Rows": "&#128230;",
    "Columns": "&#128209;",
    "Numeric Features": "&#128290;",
    "Categorical Features": "&#127991;",
    "Missing Values": "&#10067;",
    "Duplicate Rows": "&#128260;",
    "Memory Usage": "&#128190;",
    "Data Quality Score": "&#11088;",
}


def render_kpi_cards(kpis: Dict[str, str]) -> str:
    cards = []
    for label, value in kpis.items():
        icon = _KPI_ICONS.get(label, "&#128202;")
        cards.append(f"""
        <div class="kpi-card">
            <div class="kpi-icon">{icon}</div>
            <div class="kpi-value">{value}</div>
            <div class="kpi-label">{label}</div>
        </div>
        """)
    return f'<div class="kpi-grid">{"".join(cards)}</div>'


def _health_color(score: float) -> str:
    if score >= 80:
        return COLOR_SUCCESS
    if score >= 50:
        return COLOR_WARNING
    return COLOR_DANGER


def render_health_score(health: Dict[str, float]) -> str:
    overall = health.get("overall", 0)
    color = _health_color(overall)
    return f"""
    <div class="health-card">
        <div class="health-ring" style="--pct:{overall}; --color:{color};">
            <span class="health-score">{overall}</span>
        </div>
        <div class="health-breakdown">
            <div><span class="dot" style="background:{COLOR_PRIMARY}; color:{COLOR_PRIMARY}"></span> Completeness: {health.get('completeness', 0)}%</div>
            <div><span class="dot" style="background:{COLOR_ACCENT}; color:{COLOR_ACCENT}"></span> Uniqueness: {health.get('uniqueness', 0)}%</div>
            <div><span class="dot" style="background:{COLOR_SUCCESS}; color:{COLOR_SUCCESS}"></span> Consistency: {health.get('consistency', 0)}%</div>
        </div>
    </div>
    """


def render_insight_list(items: List[str], empty_message: str = "No insights available yet.") -> str:
    if not items:
        return f'<div class="insight-empty">{empty_message}</div>'
    rows = "".join(f'<li class="insight-item">{item}</li>' for item in items)
    return f'<ul class="insight-list">{rows}</ul>'


def render_section_title(title: str, subtitle: str = "") -> str:
    sub_html = f'<p class="section-subtitle">{subtitle}</p>' if subtitle else ""
    return f'<div class="section-header"><h2>{title}</h2>{sub_html}</div>'


# =============================================================================
# GRADIO APP - PREMIUM SIDEBAR SAAS LAYOUT
# =============================================================================

# Page registry used to drive sidebar navigation + visibility switching.
# Order here defines the order of buttons in the sidebar.
PAGE_NAMES: Final[list] = [
    "Dashboard",
    "Analytics",
    "Visualizations",
    "Machine Learning",
    "Forecasting",
    "Reports",
    "Settings",
]

PAGE_ICONS: Final[dict] = {
    "Dashboard": "🏠",
    "Analytics": "📈",
    "Visualizations": "📊",
    "Machine Learning": "🤖",
    "Forecasting": "🔮",
    "Reports": "📄",
    "Settings": "⚙️",
}

CUSTOM_CSS = """
/* =============================================================
   FONTS & ROOT VARIABLES
   ============================================================= */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');

:root {
    --bg: #080A14;
    --card: #131628;
    --card-soft: #181D34;
    --card-border: #2A2F4A;
    --primary: #7C5CFC;
    --primary-light: #A78BFA;
    --primary-dark: #5B3FE0;
    --accent: #1FE3B8;
    --accent-dark: #14B894;
    --success: #34D399;
    --warning: #FBBF24;
    --danger: #FB7185;
    --text: #F1F2F8;
    --text-muted: #9499B7;
    --radius-lg: 20px;
    --radius-md: 14px;
    --radius-sm: 10px;
    --shadow-card: 0 8px 28px rgba(0, 0, 0, 0.45);
    --shadow-glow: 0 8px 30px rgba(124, 92, 252, 0.35);
    --transition: all 0.22s cubic-bezier(0.4, 0, 0.2, 1);
}

* { font-family: 'Inter', sans-serif !important; }

/* =============================================================
   GLOBAL CANVAS
   ============================================================= */
.gradio-container {
    background: radial-gradient(circle at top left, #1A1530 0%, #080A14 55%) !important;
    color: var(--text) !important;
}
footer { display: none !important; }

/* =============================================================
   HERO HEADER
   ============================================================= */
#hero-header {
    position: relative;
    padding: 42px 40px;
    border-radius: var(--radius-lg);
    background: linear-gradient(135deg, #100E21 0%, #1B1438 45%, #0E1A2E 100%);
    border: 1px solid rgba(255, 255, 255, 0.08);
    box-shadow: 0 25px 70px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255,255,255,0.04);
    text-align: center;
    margin-bottom: 20px;
    overflow: hidden;
}
#hero-header::before {
    content: "";
    position: absolute;
    top: -60%; left: 50%;
    width: 480px; height: 320px;
    transform: translateX(-50%);
    background: radial-gradient(circle, rgba(124, 92, 252, 0.35), transparent 70%);
    pointer-events: none;
}
#hero-header::after {
    content: "";
    position: absolute;
    bottom: -70%; right: 5%;
    width: 380px; height: 280px;
    background: radial-gradient(circle, rgba(31, 227, 184, 0.22), transparent 70%);
    pointer-events: none;
}
.hero-badge {
    position: relative;
    display: inline-block;
    padding: 7px 18px;
    margin-bottom: 16px;
    background: rgba(31, 227, 184, 0.12);
    border: 1px solid rgba(31, 227, 184, 0.35);
    border-radius: 999px;
    font-size: 11.5px;
    font-weight: 700;
    letter-spacing: 2.2px;
    color: #4FF0CF;
    text-transform: uppercase;
}
#hero-header h1 {
    position: relative;
    font-size: 52px;
    font-weight: 900;
    margin: 0;
    letter-spacing: -1.8px;
    color: #ffffff;
    line-height: 1.05;
}
#hero-header h1 span {
    color: var(--accent);
    background: linear-gradient(90deg, #1FE3B8, #7C5CFC);
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
}
#hero-header p {
    position: relative;
    margin-top: 14px;
    font-size: 14.5px;
    font-weight: 500;
    color: #B9BEDC;
    letter-spacing: 0.5px;
}

/* =============================================================
   SIDEBAR
   ============================================================= */
#sidebar-card {
    background: linear-gradient(160deg, rgba(19, 22, 40, 0.92) 0%, rgba(11, 13, 24, 0.96) 100%);
    border: 1px solid var(--card-border);
    border-radius: var(--radius-lg);
    padding: 22px 16px;
    backdrop-filter: blur(16px);
    box-shadow: var(--shadow-card), inset 0 1px 0 rgba(255,255,255,0.03);
    position: sticky;
    top: 12px;
}
#sidebar-logo {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 4px 8px 18px 8px;
    border-bottom: 1px solid var(--card-border);
    margin-bottom: 14px;
}
#sidebar-logo .logo-mark {
    font-size: 20px;
    width: 38px; height: 38px;
    border-radius: 12px;
    background: linear-gradient(135deg, var(--primary), var(--accent));
    display: flex; align-items: center; justify-content: center;
    box-shadow: 0 6px 18px rgba(124, 92, 252, 0.5);
}
#sidebar-logo .logo-text {
    font-size: 18px;
    font-weight: 800;
    color: var(--text);
    letter-spacing: -0.3px;
}
#sidebar-logo .logo-text span {
    color: var(--accent);
    background: linear-gradient(90deg, #1FE3B8, #A78BFA);
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
}

#sidebar-card .gr-button {
    width: 100% !important;
    justify-content: flex-start !important;
    text-align: left !important;
    background: transparent !important;
    border: 1px solid transparent !important;
    border-left: 3px solid transparent !important;
    color: var(--text-muted) !important;
    font-weight: 600 !important;
    font-size: 14px !important;
    border-radius: var(--radius-sm) !important;
    padding: 11px 14px !important;
    margin-bottom: 6px !important;
    box-shadow: none !important;
    transition: var(--transition) !important;
}
#sidebar-card .gr-button:hover {
    background: rgba(124, 92, 252, 0.12) !important;
    color: var(--text) !important;
    transform: translateX(3px);
}
#sidebar-card .nav-btn-active {
    background: linear-gradient(135deg, rgba(124, 92, 252, 0.22), rgba(31, 227, 184, 0.08)) !important;
    border-left: 3px solid var(--accent) !important;
    color: #ffffff !important;
    box-shadow: inset 0 0 0 1px rgba(124, 92, 252, 0.3) !important;
    font-weight: 700 !important;
}
#sidebar-card .nav-btn-active:hover { transform: none; }

#sidebar-footer {
    margin-top: 16px;
    padding-top: 14px;
    border-top: 1px solid var(--card-border);
    font-size: 11px;
    color: var(--text-muted);
    text-align: center;
    letter-spacing: 0.6px;
    text-transform: uppercase;
}

/* =============================================================
   CONTENT AREA / PAGE CARDS
   ============================================================= */
#content-card {
    position: relative;
    background: linear-gradient(160deg, rgba(19, 22, 40, 0.65) 0%, rgba(11, 13, 24, 0.55) 100%);
    border: 1px solid var(--card-border);
    border-radius: var(--radius-lg);
    padding: 28px 30px;
    min-height: 70vh;
    box-shadow: var(--shadow-card);
    backdrop-filter: blur(10px);
}
.gr-panel, .gradio-container .block { border-radius: var(--radius-md) !important; }
.tabitem, .tabs { border-radius: var(--radius-md) !important; }

.page-title-row {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 4px;
}
.page-title-row .page-icon { font-size: 22px; }
.section-header { margin-bottom: 6px; }
.section-header h2 {
    font-size: 20px;
    font-weight: 800;
    margin-bottom: 3px;
    color: var(--text);
    letter-spacing: -0.3px;
}
.section-subtitle { color: var(--text-muted); font-size: 13px; margin: 0 0 16px 0; }

/* =============================================================
   UPLOAD CARD
   ============================================================= */
#upload-card {
    background: linear-gradient(160deg, var(--card) 0%, var(--card-soft) 100%);
    border: 1.5px dashed var(--card-border);
    border-radius: var(--radius-md);
    padding: 18px;
    transition: var(--transition);
}
#upload-card:hover { border-color: var(--primary); }

/* =============================================================
   KPI GRID
   ============================================================= */
.kpi-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(170px, 1fr));
    gap: 16px;
    margin: 10px 0 24px 0;
}
.kpi-card {
    position: relative;
    background: linear-gradient(160deg, var(--card) 0%, var(--card-soft) 100%);
    border: 1px solid var(--card-border);
    border-radius: var(--radius-md);
    padding: 22px 18px;
    text-align: center;
    box-shadow: var(--shadow-card);
    backdrop-filter: blur(8px);
    transition: var(--transition);
    overflow: hidden;
}
.kpi-card::before {
    content: "";
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 3px;
    background: linear-gradient(90deg, var(--primary), var(--accent));
    opacity: 0.6;
    transition: var(--transition);
}
.kpi-card:hover {
    transform: translateY(-5px);
    box-shadow: var(--shadow-glow);
    border-color: var(--primary);
}
.kpi-card:hover::before { opacity: 1; height: 4px; }
.kpi-icon {
    font-size: 20px;
    margin-bottom: 10px;
    width: 42px; height: 42px;
    line-height: 42px;
    margin-left: auto; margin-right: auto;
    border-radius: 12px;
    background: linear-gradient(135deg, rgba(124,92,252,0.18), rgba(31,227,184,0.12));
    border: 1px solid rgba(124,92,252,0.25);
}
.kpi-value {
    font-size: 24px;
    font-weight: 800;
    color: var(--accent);
    letter-spacing: -0.3px;
}
.kpi-label {
    font-size: 12px;
    color: var(--text-muted);
    margin-top: 6px;
    letter-spacing: 0.4px;
    font-weight: 600;
    text-transform: uppercase;
}

/* =============================================================
   HEALTH SCORE CARD
   ============================================================= */
.health-card {
    display: flex; align-items: center; gap: 30px;
    background: linear-gradient(160deg, var(--card) 0%, var(--card-soft) 100%);
    border: 1px solid var(--card-border);
    border-radius: var(--radius-lg);
    padding: 26px 30px;
    margin-bottom: 24px;
    box-shadow: var(--shadow-card);
}
.health-ring {
    --pct: 0; --color: #34D399;
    width: 108px; height: 108px; border-radius: 50%;
    background: conic-gradient(var(--color) calc(var(--pct) * 1%), #1E2238 0);
    display: flex; align-items: center; justify-content: center;
    position: relative; flex-shrink: 0;
    transition: var(--transition);
    box-shadow: 0 0 24px rgba(124, 92, 252, 0.25);
}
.health-ring::before {
    content: ""; position: absolute; width: 82px; height: 82px;
    background: var(--card); border-radius: 50%;
}
.health-score { position: relative; font-size: 26px; font-weight: 800; color: var(--text); }
.health-breakdown { font-size: 13.5px; color: var(--text-muted); line-height: 2.1; font-weight: 500; }
.health-breakdown .dot {
    display: inline-block; width: 9px; height: 9px; border-radius: 50%; margin-right: 7px;
    box-shadow: 0 0 8px currentColor;
}

/* =============================================================
   INSIGHT LISTS
   ============================================================= */
.insight-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 10px; }
.insight-item {
    background: linear-gradient(160deg, var(--card) 0%, var(--card-soft) 100%);
    border-left: 3px solid var(--primary);
    border-radius: var(--radius-sm);
    padding: 14px 17px;
    font-size: 13.8px;
    color: var(--text);
    line-height: 1.55;
    box-shadow: 0 3px 14px rgba(0, 0, 0, 0.3);
    transition: var(--transition);
}
.insight-item:hover {
    transform: translateX(3px);
    border-left-color: var(--accent);
    box-shadow: 0 6px 20px rgba(31, 227, 184, 0.15);
}
.insight-empty { color: var(--text-muted); font-style: italic; padding: 10px 0; }

/* =============================================================
   CHART CARD WRAPPERS
   ============================================================= */
.chart-card-wrap > div {
    background: linear-gradient(160deg, var(--card) 0%, var(--card-soft) 100%) !important;
    border: 1px solid var(--card-border) !important;
    border-radius: var(--radius-md) !important;
    padding: 14px !important;
    box-shadow: var(--shadow-card);
}

/* =============================================================
   BUTTONS
   ============================================================= */
button.primary, .gr-button-primary {
    background: linear-gradient(135deg, var(--primary), var(--primary-dark)) !important;
    border: none !important;
    border-radius: var(--radius-sm) !important;
    box-shadow: var(--shadow-glow) !important;
    transition: var(--transition) !important;
    font-weight: 700 !important;
    letter-spacing: 0.2px !important;
}
button.primary:hover, .gr-button-primary:hover {
    transform: translateY(-2px);
    box-shadow: 0 14px 36px rgba(124, 92, 252, 0.55) !important;
}
.gr-button-secondary {
    border-radius: var(--radius-sm) !important;
    transition: var(--transition) !important;
}

/* =============================================================
   ACCORDIONS
   ============================================================= */
.accordion, .gr-accordion {
    border-radius: var(--radius-md) !important;
    border: 1px solid var(--card-border) !important;
    margin-bottom: 12px !important;
    background: linear-gradient(160deg, rgba(19,22,40,0.5) 0%, rgba(11,13,24,0.4) 100%) !important;
}

/* =============================================================
   RESPONSIVE
   ============================================================= */
@media (max-width: 1024px) {
    #hero-header h1 { font-size: 36px; }
    .kpi-grid { grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); }
    .health-card { flex-direction: column; text-align: center; }
}
@media (max-width: 768px) {
    #sidebar-card { position: static; }
    #content-card { padding: 16px; }
}
"""


def _empty_fig_placeholder():
    fig = go.Figure()
    fig.update_layout(
        template="plotly_dark",
        annotations=[dict(text="No data available for this chart", showarrow=False,
                           font=dict(size=14, color="#9CA3AF"))],
        paper_bgcolor="#0B0F19", plot_bgcolor="#141927",
    )
    return fig


def load_csv(file_obj) -> Tuple[Optional[pd.DataFrame], str]:
    if file_obj is None:
        return None, "Please upload a CSV file to begin."

    path = file_obj if isinstance(file_obj, str) else file_obj.name
    if not str(path).lower().endswith(SUPPORTED_EXTENSIONS):
        return None, "Unsupported file type. Please upload a .csv file."

    try:
        df = pd.read_csv(path)
    except pd.errors.EmptyDataError:
        return None, "The uploaded file is empty."
    except UnicodeDecodeError:
        try:
            df = pd.read_csv(path, encoding="latin1")
        except Exception as e:
            return None, f"Could not decode file: {e}"
    except Exception as e:
        return None, f"Error reading CSV: {e}"

    if df.empty:
        return None, "The dataset contains no rows."
    if df.shape[1] == 0:
        return None, "The dataset contains no columns."

    return df, f"Successfully loaded **{path.split('/')[-1]}** - {df.shape[0]:,} rows x {df.shape[1]} columns."


def _pick_default_regression_target(df: pd.DataFrame) -> Optional[str]:
    """Pick a sensible default numeric target - avoids empty or mostly-missing
    numeric columns (e.g. a blank 'notes' column) that would otherwise make
    every downstream ML call fail immediately."""
    usable = _usable_numeric_columns(df)
    if usable:
        return usable[-1]
    return df.columns.tolist()[0] if len(df.columns) else None


def _pick_default_classification_target(df: pd.DataFrame) -> Optional[str]:
    """Pick a sensible default target for tree/forest tools - prefers a
    categorical column with reasonable cardinality, avoiding ID/date-like
    columns that have near-unique values per row."""
    cat_cols = categorical_columns(df)
    for col in cat_cols:
        if 1 < df[col].nunique() <= 20:
            return col
    num_cols = numeric_columns(df)
    for col in num_cols:
        if 1 < df[col].nunique() <= 10:
            return col
    return df.columns.tolist()[0] if len(df.columns) else None


def on_file_upload(file_obj):
    df, message = load_csv(file_obj)
    if df is None:
        empty_html = render_insight_list([], "Upload a valid CSV to see results.")
        return (
            None, message,
            pd.DataFrame(), "", "", empty_html, empty_html,
            gr.update(choices=[]), gr.update(choices=[]), gr.update(choices=[]), gr.update(choices=[]),
        )

    kpis = compute_kpis(df)
    health = dataset_health_score(df)
    kpi_html = render_kpi_cards(kpis)
    health_html = render_health_score(health)

    col_info = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str).values,
        "Missing": df.isna().sum().values,
        "Unique Values": [df[c].nunique() for c in df.columns],
    })

    all_cols = df.columns.tolist()
    num_cols = numeric_columns(df)
    usable_num_cols = _usable_numeric_columns(df)
    cat_cols = categorical_columns(df)

    return (
        df, message,
        df.head(10), col_info, kpi_html, health_html,
        render_insight_list([], "Click 'Generate Insights' below to see business insights."),
        gr.update(choices=all_cols, value=usable_num_cols[0] if usable_num_cols else None),
        gr.update(choices=all_cols, value=usable_num_cols[1] if len(usable_num_cols) > 1 else None),
        gr.update(choices=cat_cols, value=cat_cols[0] if cat_cols else None),
        gr.update(choices=usable_num_cols, value=usable_num_cols[0] if usable_num_cols else None),
    )


def on_clean_data(df, strategy):
    if df is None or df.empty:
        return df, "Upload a dataset first.", pd.DataFrame()
    try:
        cleaner = DataCleaner(df)
        cleaned_df, log = cleaner.run_full_pipeline()
        log_text = "\n".join(f"- {line}" for line in log)
        return cleaned_df, log_text, cleaned_df.head(10)
    except Exception as e:
        return df, f"Cleaning failed: {e}\n{traceback.format_exc()[-400:]}", df.head(10)


def on_generate_insights(df):
    if df is None or df.empty:
        empty = render_insight_list([], "Upload a dataset first.")
        return empty, empty
    try:
        insights = generate_business_insights(df)
        recommendations = generate_recommendations(df)
        return render_insight_list(insights), render_insight_list(recommendations)
    except Exception as e:
        err = render_insight_list([f"Error generating insights: {e}"])
        return err, err


def on_generate_charts(df):
    if df is None or df.empty:
        ph = _empty_fig_placeholder()
        return [ph] * 8

    figs = auto_select_charts(df)
    order = [
        "Bar Chart", "Line Chart", "Pie Chart", "Scatter Plot",
        "Histogram", "Box Plot", "Violin Plot", "Correlation Heatmap",
    ]
    output = []
    for key in order:
        output.append(figs.get(key, _empty_fig_placeholder()))
    return output


def on_custom_scatter(df, x_col, y_col, color_col):
    if df is None or df.empty or not x_col or not y_col:
        return _empty_fig_placeholder()
    fig = scatter_plot(df, x_col, y_col, color_col if color_col else None)
    return fig if fig is not None else _empty_fig_placeholder()


def on_stats_run(df):
    if df is None or df.empty:
        empty = pd.DataFrame()
        return empty, empty, empty, empty, empty, _empty_fig_placeholder()
    desc = descriptive_summary(df)
    skew_kurt = skewness_kurtosis(df)
    normality = normality_check(df)
    variance = variance_analysis(df)

    outliers_iqr = detect_outliers_iqr(df)
    outliers_z = detect_outliers_zscore(df)
    outlier_df = pd.DataFrame({
        "Column": list(outliers_iqr.keys()),
        "Outliers (IQR)": list(outliers_iqr.values()),
        "Outliers (Z-Score)": [outliers_z.get(c, 0) for c in outliers_iqr.keys()],
    })

    heatmap = correlation_heatmap(df)
    heatmap = heatmap if heatmap is not None else _empty_fig_placeholder()

    return desc.reset_index().rename(columns={"index": "Column"}), skew_kurt, normality, variance, outlier_df, heatmap


def on_ml_kmeans(df, n_clusters):
    if df is None or df.empty:
        return _empty_fig_placeholder(), "Upload a dataset first."
    fig, summary = run_kmeans(df, int(n_clusters))
    return fig if fig is not None else _empty_fig_placeholder(), summary


def on_ml_regression(df, target_col):
    if df is None or df.empty or not target_col:
        return _empty_fig_placeholder(), "Select a target column first."
    fig, summary = run_linear_regression(df, target_col)
    return fig if fig is not None else _empty_fig_placeholder(), summary


def on_ml_rf_importance(df, target_col):
    if df is None or df.empty or not target_col:
        return _empty_fig_placeholder(), "Select a target column first."
    fig, summary = run_random_forest_importance(df, target_col)
    return fig if fig is not None else _empty_fig_placeholder(), summary


def on_ml_pca(df):
    if df is None or df.empty:
        return _empty_fig_placeholder(), "Upload a dataset first."
    fig, summary = run_pca(df)
    return fig if fig is not None else _empty_fig_placeholder(), summary


def on_ml_decision_tree(df, target_col, max_depth):
    if df is None or df.empty or not target_col:
        return _empty_fig_placeholder(), "Select a target column first."
    fig, summary = run_decision_tree(df, target_col, int(max_depth))
    return fig if fig is not None else _empty_fig_placeholder(), summary


def on_forecast_run(df, value_col, periods):
    if df is None or df.empty or not value_col:
        return _empty_fig_placeholder(), "Select a numeric column and ensure your dataset has a date column."

    working_df = df
    date_col = detect_date_column(working_df)

    if date_col is None:
        # Auto-attempt date conversion so forecasting works even if the user
        # hasn't manually run the cleaning pipeline first.
        working_df = df.copy()
        for col in working_df.columns:
            if pd.api.types.is_object_dtype(working_df[col]) or pd.api.types.is_string_dtype(working_df[col]):
                sample = working_df[col].dropna().astype(str).head(20)
                if sample.empty:
                    continue
                try:
                    parsed = pd.to_datetime(sample, errors="coerce", format="mixed")
                    if parsed.notna().mean() > 0.8:
                        working_df[col] = pd.to_datetime(working_df[col], errors="coerce", format="mixed")
                except Exception:
                    continue
        date_col = detect_date_column(working_df)

    if date_col is None:
        return _empty_fig_placeholder(), "No date/datetime column detected in this dataset. Forecasting needs at least one date column."

    if value_col not in numeric_columns(working_df):
        return _empty_fig_placeholder(), f"'{value_col}' is not numeric. Please select a numeric column to forecast."

    try:
        series = prepare_series(working_df, date_col, value_col, freq="ME")
        if series.dropna().empty:
            return _empty_fig_placeholder(), "Not enough data points to forecast."

        forecast_vals, method = forecast_series(series, periods=int(periods))
        fig = build_forecast_chart(series, forecast_vals, value_col, method)
        growth = compute_growth_rate(series)
        seasonality = detect_seasonality(series) or "Not enough data to assess seasonality."

        summary = (
            f"Detected date column: **{date_col}**\n"
            f"Overall growth rate: **{growth:.1f}%**\n"
            f"{seasonality}\n"
            f"Forecast method: **{method}**"
        )
        return fig, summary
    except Exception as e:
        return _empty_fig_placeholder(), f"Forecasting failed: {e}"


def on_export_csv(df):
    if df is None or df.empty:
        return None
    path = export_cleaned_csv(df)
    return path


def on_export_pdf(df, dataset_name):
    if df is None or df.empty:
        return None
    kpis = compute_kpis(df)
    insights = generate_business_insights(df)
    recommendations = generate_recommendations(df)
    path = export_business_pdf_report(
        df, kpis, insights, recommendations, dataset_name=dataset_name or "Uploaded Dataset"
    )
    return path


def on_export_summary(df):
    if df is None or df.empty:
        return None
    kpis = compute_kpis(df)
    insights = generate_business_insights(df)
    recommendations = generate_recommendations(df)
    path = export_summary_text_report(kpis, insights, recommendations)
    return path


def _make_nav_switch_fn(target_page: str):
    """Returns a callback that shows `target_page` and hides all others,
    while also updating sidebar button styling to highlight the active item."""
    def _switch(*_args):
        visibility_updates = [gr.update(visible=(p == target_page)) for p in PAGE_NAMES]
        button_updates = [
            gr.update(elem_classes=["nav-btn-active"] if p == target_page else [])
            for p in PAGE_NAMES
        ]
        return (*visibility_updates, *button_updates)
    return _switch


def build_app() -> gr.Blocks:
    with gr.Blocks(css=CUSTOM_CSS, theme=gr.themes.Base(primary_hue="indigo", neutral_hue="slate"),
                    title=f"{APP_NAME} - Smart Data Analytics Platform") as demo:

        df_state = gr.State(None)

        # ---------------------------------------------------------------
        # HERO HEADER
        # ---------------------------------------------------------------
        gr.HTML("""
<div id="hero-header">
    <div class="hero-badge">SMART DATA ANALYTICS PLATFORM</div>
    <h1>Insight<span>AI</span></h1>
    <p>Upload &bull; Analyze &bull; Visualize &bull; Forecast &bull; Export</p>
</div>
""")

        with gr.Row(equal_height=False):
            # -------------------------------------------------------
            # LEFT SIDEBAR
            # -------------------------------------------------------
            with gr.Column(scale=1, min_width=230, elem_id="sidebar-col"):
                with gr.Column(elem_id="sidebar-card"):
                    gr.HTML("""
<div id="sidebar-logo">
    <div class="logo-mark">&#128202;</div>
    <div class="logo-text">Insight<span>AI</span></div>
</div>
""")
                    nav_buttons = []
                    for page in PAGE_NAMES:
                        btn = gr.Button(
                            f"{PAGE_ICONS[page]}  {page}",
                            elem_classes=["nav-btn-active"] if page == "Dashboard" else [],
                        )
                        nav_buttons.append(btn)

                    gr.HTML(f'<div id="sidebar-footer">InsightAI v{APP_VERSION}</div>')

            # -------------------------------------------------------
            # RIGHT CONTENT AREA
            # -------------------------------------------------------
            with gr.Column(scale=5):
                with gr.Column(elem_id="content-card"):

                    # ============== DASHBOARD PAGE ==============
                    page_dashboard = gr.Column(visible=True)
                    with page_dashboard:
                        gr.HTML(render_section_title("Dashboard", "Upload a dataset to unlock KPIs, health score, and insights"))

                        with gr.Column(elem_id="upload-card"):
                            gr.Markdown("#### Upload Dataset")
                            file_input = gr.File(label="Drag & drop a CSV file", file_types=[".csv"])
                            upload_status = gr.Markdown("Awaiting upload...")
                            gr.Markdown(
                                "**Tip:** Don't have a dataset? Use the sample file in "
                                "`sample_data/sample_sales_data.csv` included with this project."
                            )

                        gr.HTML(render_section_title("Dataset Health & KPIs"))
                        health_html = gr.HTML()
                        kpi_html = gr.HTML()

                        gr.HTML(render_section_title("Dataset Preview"))
                        preview_table = gr.Dataframe(label="First 10 Rows", interactive=False)

                        gr.HTML(render_section_title("Column Information"))
                        column_info_table = gr.Dataframe(label="Schema Overview", interactive=False)

                        gr.HTML(render_section_title("Business Insights & Recommendations"))
                        insights_btn = gr.Button("Generate Insights", variant="primary")
                        with gr.Row():
                            with gr.Column():
                                gr.Markdown("#### Key Insights")
                                insights_html = gr.HTML()
                            with gr.Column():
                                gr.Markdown("#### Recommendations")
                                recommendations_html = gr.HTML()

                    # ============== ANALYTICS PAGE (Statistical Analysis) ==============
                    page_analytics = gr.Column(visible=False)
                    with page_analytics:
                        gr.HTML(render_section_title("Analytics", "Deep statistical breakdown of your dataset"))
                        stats_btn = gr.Button("Run Statistical Analysis", variant="primary")
                        with gr.Column(elem_classes=["chart-card-wrap"]):
                            stats_heatmap = gr.Plot(label="Correlation Matrix")
                        with gr.Row():
                            desc_table = gr.Dataframe(label="Descriptive Summary")
                            variance_table = gr.Dataframe(label="Variance Analysis")
                        with gr.Row():
                            skew_table = gr.Dataframe(label="Skewness & Kurtosis")
                            normality_table = gr.Dataframe(label="Normality Check (Shapiro-Wilk)")
                        outlier_table = gr.Dataframe(label="Outlier Detection (IQR vs Z-Score)")

                    # ============== VISUALIZATIONS PAGE ==============
                    page_visualizations = gr.Column(visible=False)
                    with page_visualizations:
                        gr.HTML(render_section_title(
                            "Visualizations", "Charts are auto-selected based on your column types"
                        ))
                        chart_btn = gr.Button("Generate Auto Charts", variant="primary")
                        with gr.Row():
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_bar = gr.Plot(label="Bar Chart")
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_line = gr.Plot(label="Line Chart")
                        with gr.Row():
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_pie = gr.Plot(label="Pie Chart")
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_scatter = gr.Plot(label="Scatter Plot")
                        with gr.Row():
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_hist = gr.Plot(label="Histogram")
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_box = gr.Plot(label="Box Plot")
                        with gr.Row():
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_violin = gr.Plot(label="Violin Plot")
                            with gr.Column(elem_classes=["chart-card-wrap"]):
                                chart_heatmap = gr.Plot(label="Correlation Heatmap")

                        gr.HTML(render_section_title("Custom Scatter Explorer"))
                        with gr.Row():
                            x_dropdown = gr.Dropdown(label="X Axis", choices=[])
                            y_dropdown = gr.Dropdown(label="Y Axis", choices=[])
                            color_dropdown = gr.Dropdown(label="Color By (optional)", choices=[])
                        with gr.Column(elem_classes=["chart-card-wrap"]):
                            custom_scatter_plot = gr.Plot(label="Custom Scatter")

                    # ============== MACHINE LEARNING PAGE ==============
                    page_ml = gr.Column(visible=False)
                    with page_ml:
                        gr.HTML(render_section_title("Machine Learning", "Runs 100% locally via scikit-learn"))

                        with gr.Accordion("K-Means Clustering", open=True):
                            kmeans_n = gr.Slider(2, 8, value=3, step=1, label="Number of Clusters")
                            kmeans_btn = gr.Button("Run K-Means")
                            kmeans_plot = gr.Plot()
                            kmeans_summary = gr.Markdown()

                        with gr.Accordion("Linear Regression"):
                            reg_target = gr.Dropdown(label="Target Column (numeric)", choices=[])
                            reg_btn = gr.Button("Run Linear Regression")
                            reg_plot = gr.Plot()
                            reg_summary = gr.Markdown()

                        with gr.Accordion("Decision Tree (Classification/Regression)"):
                            tree_target = gr.Dropdown(label="Target Column", choices=[])
                            tree_depth = gr.Slider(2, 10, value=4, step=1, label="Max Depth")
                            tree_btn = gr.Button("Run Decision Tree")
                            tree_plot = gr.Plot()
                            tree_summary = gr.Markdown()

                        with gr.Accordion("Random Forest Feature Importance"):
                            rf_target = gr.Dropdown(label="Target Column", choices=[])
                            rf_btn = gr.Button("Compute Feature Importance")
                            rf_plot = gr.Plot()
                            rf_summary = gr.Markdown()

                        with gr.Accordion("PCA Visualization"):
                            pca_btn = gr.Button("Run PCA")
                            pca_plot = gr.Plot()
                            pca_summary = gr.Markdown()

                    # ============== FORECASTING PAGE ==============
                    page_forecasting = gr.Column(visible=False)
                    with page_forecasting:
                        gr.HTML(render_section_title(
                            "Forecasting", "Auto-detects date columns - Holt's Linear Trend model"
                        ))
                        with gr.Row():
                            forecast_col = gr.Dropdown(label="Numeric Column to Forecast", choices=[])
                            forecast_periods = gr.Slider(1, 24, value=6, step=1, label="Periods Ahead (months)")
                        forecast_btn = gr.Button("Generate Forecast", variant="primary")
                        with gr.Column(elem_classes=["chart-card-wrap"]):
                            forecast_plot = gr.Plot()
                        forecast_summary = gr.Markdown()

                    # ============== REPORTS PAGE (Download Center) ==============
                    page_reports = gr.Column(visible=False)
                    with page_reports:
                        gr.HTML(render_section_title("Reports", "Export your cleaned data, business report, and summary"))
                        dataset_name_input = gr.Textbox(label="Dataset Name (for report title)", value="Uploaded Dataset")
                        with gr.Row():
                            export_csv_btn = gr.Button("Export Cleaned CSV")
                            export_pdf_btn = gr.Button("Export Business PDF Report")
                            export_summary_btn = gr.Button("Export Summary Report")
                        with gr.Row():
                            csv_file_out = gr.File(label="Cleaned CSV")
                            pdf_file_out = gr.File(label="Business PDF Report")
                            summary_file_out = gr.File(label="Summary Report (TXT)")

                    # ============== SETTINGS PAGE ==============
                    page_settings = gr.Column(visible=False)
                    with page_settings:
                        gr.HTML(render_section_title("Settings", "About this platform"))
                        gr.Markdown(
                            f"""
**InsightAI** &nbsp;|&nbsp; Version **{APP_VERSION}**

- 100% offline analytics engine - no external AI APIs, no internet dependency for analysis
- Built with Gradio, Pandas, NumPy, Plotly, Scikit-Learn, SciPy, Statsmodels, ReportLab
- All cleaning, statistics, ML, and forecasting run locally inside this Colab session
- Exported files (CSV / PDF / TXT) are written to the `outputs/` folder
- Cleaning strategy and forecast horizon can be adjusted directly on their respective pages

**Data Cleaning Strategy** (applies on the Dashboard's cleaning step):
"""
                        )
                        clean_strategy = gr.Radio(
                            ["smart", "drop", "zero"], value="smart", label="Missing Value Strategy",
                            info="smart = median/mode fill, drop = remove rows, zero = fill with 0/Unknown",
                        )
                        clean_btn = gr.Button("Run Full Cleaning Pipeline", variant="primary")
                        clean_log = gr.Textbox(label="Cleaning Report", lines=8, interactive=False)
                        cleaned_preview = gr.Dataframe(label="Cleaned Data Preview", interactive=False)

        # =========================================================================
        # SIDEBAR NAVIGATION WIRING
        # =========================================================================
        all_pages = [
            page_dashboard, page_analytics, page_visualizations,
            page_ml, page_forecasting, page_reports, page_settings,
        ]

        for page_name, btn in zip(PAGE_NAMES, nav_buttons):
            btn.click(
                _make_nav_switch_fn(page_name),
                inputs=[],
                outputs=[*all_pages, *nav_buttons],
            )

        # =========================================================================
        # FEATURE WIRING (unchanged business logic / callbacks)
        # =========================================================================
        file_input.upload(
            on_file_upload, inputs=[file_input],
            outputs=[
                df_state, upload_status, preview_table, column_info_table,
                kpi_html, health_html, insights_html,
                x_dropdown, y_dropdown, color_dropdown, forecast_col,
            ],
        ).then(
            lambda df: (
                gr.update(
                    choices=df.columns.tolist() if df is not None else [],
                    value=(
                        (_pick_default_regression_target(df) if df is not None and len(df.columns) else None)
                    ),
                ),
                gr.update(
                    choices=df.columns.tolist() if df is not None else [],
                    value=(_pick_default_classification_target(df) if df is not None and len(df.columns) else None),
                ),
                gr.update(
                    choices=df.columns.tolist() if df is not None else [],
                    value=(
                        (_pick_default_regression_target(df) if df is not None and len(df.columns) else None)
                    ),
                ),
                gr.update(
                    choices=_usable_numeric_columns(df) if df is not None else [],
                    value=(_pick_default_regression_target(df) if df is not None and len(df.columns) else None),
                ),
            ),
            inputs=[df_state],
            outputs=[reg_target, tree_target, rf_target, forecast_col],
        )

        clean_btn.click(
            on_clean_data, inputs=[df_state, clean_strategy],
            outputs=[df_state, clean_log, cleaned_preview],
        )

        chart_btn.click(
            on_generate_charts, inputs=[df_state],
            outputs=[chart_bar, chart_line, chart_pie, chart_scatter, chart_hist, chart_box, chart_violin, chart_heatmap],
        )

        for trigger in [x_dropdown, y_dropdown, color_dropdown]:
            trigger.change(
                on_custom_scatter, inputs=[df_state, x_dropdown, y_dropdown, color_dropdown],
                outputs=[custom_scatter_plot],
            )

        insights_btn.click(
            on_generate_insights, inputs=[df_state],
            outputs=[insights_html, recommendations_html],
        )

        stats_btn.click(
            on_stats_run, inputs=[df_state],
            outputs=[desc_table, skew_table, normality_table, variance_table, outlier_table, stats_heatmap],
        )

        kmeans_btn.click(on_ml_kmeans, inputs=[df_state, kmeans_n], outputs=[kmeans_plot, kmeans_summary])
        reg_btn.click(on_ml_regression, inputs=[df_state, reg_target], outputs=[reg_plot, reg_summary])
        tree_btn.click(on_ml_decision_tree, inputs=[df_state, tree_target, tree_depth], outputs=[tree_plot, tree_summary])
        rf_btn.click(on_ml_rf_importance, inputs=[df_state, rf_target], outputs=[rf_plot, rf_summary])
        pca_btn.click(on_ml_pca, inputs=[df_state], outputs=[pca_plot, pca_summary])

        forecast_btn.click(
            on_forecast_run, inputs=[df_state, forecast_col, forecast_periods],
            outputs=[forecast_plot, forecast_summary],
        )

        export_csv_btn.click(on_export_csv, inputs=[df_state], outputs=[csv_file_out])
        export_pdf_btn.click(on_export_pdf, inputs=[df_state, dataset_name_input], outputs=[pdf_file_out])
        export_summary_btn.click(on_export_summary, inputs=[df_state], outputs=[summary_file_out])

    return demo


if __name__ == "__main__":
    app = build_app()
    app.launch(share=True, debug=False)

